// export const metadat122a = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
import {Montserrat} from 'next/font/google'

import '@/shared/style/global.scss'
import {Header} from '@/widgets'

const montserrat = Montserrat({subsets: ['cyrillic']})

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				<Header />
				{children}
			</body>
		</html>
	)
}
